name: Self-Hosted Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Pull Latest Code
        run: |
          set -e

          cd /var/www/my-app

          git fetch origin main
          git reset --hard origin/main

          echo "Deployment berhasil"